import type { MenuItem, MenuResponse } from '../stores/orders.store';

const items: MenuItem[] = [
  // ─── CHEF SPECIALS ───────────────────────────────
  {
    id: 'demo-wagyu',
    name: 'Hokkaido wagyu, charcoal seared.',
    description:
      'Dry-aged 21 days. With burnt scallion oil, kombu salt, and a single perfect leaf of shiso.',
    price: 8400,
    category: 'chef_specials',
    dietaryTags: ['gluten_free'],
    allergens: [],
    imageUrl: null,
    prepTimeMinutes: 24,
    availableFrom: null,
    availableTo: null,
  },
  {
    id: 'demo-tasting',
    name: 'Chef Aoyama, seven-course tasting.',
    description:
      'A quiet progression through the cedar room — seasonal, paced, and entirely chef-led.',
    price: 18000,
    category: 'chef_specials',
    dietaryTags: [],
    allergens: ['shellfish', 'soy'],
    imageUrl: null,
    prepTimeMinutes: 95,
    availableFrom: null,
    availableTo: null,
  },

  // ─── MAINS ───────────────────────────────────────
  {
    id: 'demo-cod',
    name: 'Black cod, miso glazed.',
    description:
      'Slow-marinated four days. With a brush of yuzu and a single nasturtium leaf.',
    price: 6200,
    category: 'mains',
    dietaryTags: ['pescatarian'],
    allergens: ['fish', 'soy'],
    imageUrl: null,
    prepTimeMinutes: 22,
    availableFrom: null,
    availableTo: null,
  },
  {
    id: 'demo-risotto',
    name: 'Truffle risotto, aged parmigiano.',
    description:
      'Carnaroli rice, white winter truffle shaved at the door. Vegetarian.',
    price: 5400,
    category: 'mains',
    dietaryTags: ['vegetarian'],
    allergens: ['dairy'],
    imageUrl: null,
    prepTimeMinutes: 18,
    availableFrom: null,
    availableTo: null,
  },
  {
    id: 'demo-aubergine',
    name: 'Charred aubergine, tahini & honey.',
    description:
      'Cooked over binchotan. Sesame, golden raisins, smoked sea salt.',
    price: 3800,
    category: 'mains',
    dietaryTags: ['vegan'],
    allergens: ['sesame'],
    imageUrl: null,
    prepTimeMinutes: 14,
    availableFrom: null,
    availableTo: null,
  },
  {
    id: 'demo-lamb',
    name: 'Rack of lamb, juniper crust.',
    description:
      'From the Yamanashi farm. Roasted root vegetables, mint oil, a glass of pinot.',
    price: 7200,
    category: 'mains',
    dietaryTags: ['gluten_free'],
    allergens: [],
    imageUrl: null,
    prepTimeMinutes: 28,
    availableFrom: null,
    availableTo: null,
  },

  // ─── BEVERAGES ───────────────────────────────────
  {
    id: 'demo-margaux',
    name: 'Château Margaux, 2015.',
    description: 'Bordeaux. A full bottle, decanted at your suite door.',
    price: 28000,
    category: 'beverage',
    dietaryTags: [],
    allergens: ['sulphites'],
    imageUrl: null,
    prepTimeMinutes: 10,
    availableFrom: null,
    availableTo: null,
  },
  {
    id: 'demo-echezeaux',
    name: 'Echezeaux Grand Cru, 2012.',
    description: 'Burgundy. Of the night — the sommelier insists.',
    price: 42000,
    category: 'beverage',
    dietaryTags: [],
    allergens: ['sulphites'],
    imageUrl: null,
    prepTimeMinutes: 10,
    availableFrom: null,
    availableTo: null,
  },
  {
    id: 'demo-koshu',
    name: 'Koshu reserve, 2019.',
    description: 'Yamanashi. Crisp, mineral, perfectly cold.',
    price: 7800,
    category: 'beverage',
    dietaryTags: [],
    allergens: ['sulphites'],
    imageUrl: null,
    prepTimeMinutes: 8,
    availableFrom: null,
    availableTo: null,
  },
  {
    id: 'demo-sake',
    name: 'Sake junmai, Niigata 2022.',
    description: 'A quiet pour. Served slightly chilled in a cypress masu.',
    price: 4200,
    category: 'beverage',
    dietaryTags: ['vegan'],
    allergens: [],
    imageUrl: null,
    prepTimeMinutes: 6,
    availableFrom: null,
    availableTo: null,
  },
  {
    id: 'demo-cappuccino',
    name: 'Filter cappuccino, oat.',
    description: 'Single-origin Ethiopian beans, foamed oat milk.',
    price: 480,
    category: 'beverage',
    dietaryTags: ['vegan'],
    allergens: [],
    imageUrl: null,
    prepTimeMinutes: 8,
    availableFrom: null,
    availableTo: null,
  },

  // ─── DESSERTS ────────────────────────────────────
  {
    id: 'demo-yuzu',
    name: 'Yuzu tart, white chocolate.',
    description: 'Cold, bright, sharp. A small almond shortbread base.',
    price: 1800,
    category: 'dessert',
    dietaryTags: ['vegetarian'],
    allergens: ['dairy', 'nuts', 'gluten'],
    imageUrl: null,
    prepTimeMinutes: 6,
    availableFrom: null,
    availableTo: null,
  },
  {
    id: 'demo-matcha',
    name: 'Matcha mille feuille, brûlée.',
    description: 'Twelve thin layers, ceremonial matcha, a torched sugar lid.',
    price: 2200,
    category: 'dessert',
    dietaryTags: ['vegetarian'],
    allergens: ['dairy', 'gluten'],
    imageUrl: null,
    prepTimeMinutes: 9,
    availableFrom: null,
    availableTo: null,
  },

  // ─── BREAKFAST ───────────────────────────────────
  {
    id: 'demo-eggs',
    name: 'Soft eggs, sourdough, miso butter.',
    description: 'Two slow-poached. With aged miso, chives, a pinch of furikake.',
    price: 1600,
    category: 'breakfast',
    dietaryTags: ['vegetarian'],
    allergens: ['dairy', 'gluten', 'eggs', 'soy'],
    imageUrl: null,
    prepTimeMinutes: 12,
    availableFrom: '07:00',
    availableTo: '11:00',
  },
  {
    id: 'demo-congee',
    name: 'Congee, scallion oil, century egg.',
    description: 'Slow-stirred jasmine rice. A house favourite for the early hour.',
    price: 1400,
    category: 'breakfast',
    dietaryTags: [],
    allergens: ['eggs'],
    imageUrl: null,
    prepTimeMinutes: 15,
    availableFrom: '07:00',
    availableTo: '11:00',
  },

  // ─── LATE NIGHT ──────────────────────────────────
  {
    id: 'demo-ramen',
    name: 'Tonkotsu ramen, ajitama.',
    description:
      'Twelve-hour pork broth, chashu, marinated egg. The cure for any hour.',
    price: 2400,
    category: 'late_night',
    dietaryTags: [],
    allergens: ['gluten', 'soy', 'eggs'],
    imageUrl: null,
    prepTimeMinutes: 16,
    availableFrom: '22:00',
    availableTo: '02:00',
  },
  {
    id: 'demo-toast',
    name: 'Truffle toast, fontina.',
    description: 'A small indulgence — buttered brioche, melted fontina, shaved truffle.',
    price: 2100,
    category: 'late_night',
    dietaryTags: ['vegetarian'],
    allergens: ['gluten', 'dairy'],
    imageUrl: null,
    prepTimeMinutes: 10,
    availableFrom: '22:00',
    availableTo: '02:00',
  },
];

export const DEMO_MENU: MenuResponse = {
  items,
  categories: Array.from(new Set(items.map((i) => i.category))),
  recommended: [
    items.find((i) => i.id === 'demo-cod')!,
    items.find((i) => i.id === 'demo-risotto')!,
    items.find((i) => i.id === 'demo-aubergine')!,
  ],
  kitchen_open: true,
  kitchen_hours: { open: '07:00', close: '02:00' },
};
