import type { FastifyInstance } from 'fastify';

// Property content — attractions, rooms catalog. Static today; backed by the
// same data the mobile app shipped with so the wire-up is loss-less.
// `image_key` is resolved to a bundled asset on the mobile side via a fixed map.

const ATTRACTIONS = [
  {
    id: 'lake',
    categories: ['nature', 'attractions', 'family'],
    name: 'Kodaikanal Lake',
    subtitle: 'The star-shaped lake at the heart of the town.',
    why_visit:
      'A 5 km shoreline made for slow walks, paddle boats and rented cycles. Quiet at dawn, lively by mid-morning.',
    lat: 10.2378,
    lng: 77.4848,
    rating: '4.6',
    rating_count: '38.2k',
    grad_a: '#0A1E22',
    grad_b: '#143038',
    grad_c: 'rgba(40,120,130,0.60)',
    icon: 'water-outline',
    image_key: 'lake',
  },
  {
    id: 'coakers',
    categories: ['nature', 'attractions'],
    name: "Coaker's Walk",
    subtitle: 'A 1 km promenade along the cliff edge.',
    why_visit:
      "On clear days the valley opens all the way to Dolphin's Nose. Best at sunrise or just before sundown.",
    lat: 10.2335,
    lng: 77.4937,
    rating: '4.5',
    rating_count: '18.7k',
    grad_a: '#0E1A0E',
    grad_b: '#1A2C1A',
    grad_c: 'rgba(80,140,90,0.55)',
    icon: 'walk-outline',
    image_key: 'Coakers',
  },
  {
    id: 'bryant',
    categories: ['nature', 'culture', 'family'],
    name: 'Bryant Park',
    subtitle: 'A 20-acre botanical garden by the lake.',
    why_visit:
      'Hybrid roses, conifers and the annual May flower show. A peaceful afternoon stroll.',
    lat: 10.2363,
    lng: 77.4922,
    rating: '4.3',
    rating_count: '12.4k',
    grad_a: '#101A08',
    grad_b: '#1C2C10',
    grad_c: 'rgba(110,150,60,0.55)',
    icon: 'leaf-outline',
    image_key: 'Bryantpark',
  },
  {
    id: 'pillar',
    categories: ['nature', 'attractions'],
    name: 'Pillar Rocks',
    subtitle: 'Three vertical granite shafts, 122 m tall.',
    why_visit:
      'A dramatic viewpoint 8 km out of town. Often wreathed in mist — wait a minute, the curtain lifts.',
    lat: 10.2271,
    lng: 77.4528,
    rating: '4.4',
    rating_count: '21.3k',
    grad_a: '#15141A',
    grad_b: '#23202C',
    grad_c: 'rgba(120,110,150,0.45)',
    icon: 'triangle-outline',
    image_key: 'pillarrocks',
  },
  {
    id: 'berijam',
    categories: ['nature', 'hidden'],
    name: 'Berijam Lake',
    subtitle: 'A protected forest lake, deeper into the shola.',
    why_visit:
      'Permit required from the forest office. The drive winds through pristine shola jungle — bison and gaur are common sightings.',
    lat: 10.1843,
    lng: 77.3888,
    rating: '4.7',
    rating_count: '7.8k',
    grad_a: '#08160E',
    grad_b: '#0E2418',
    grad_c: 'rgba(40,110,70,0.55)',
    icon: 'trail-sign-outline',
    image_key: 'Berijam',
  },
  {
    id: 'silver',
    categories: ['nature', 'hidden'],
    name: 'Silver Cascade',
    subtitle: 'A 55 m roadside waterfall on the ghat road.',
    why_visit:
      'The first glimpse most visitors get of Kodai. Stop on the way in or out — best after the monsoon.',
    lat: 10.2630,
    lng: 77.5181,
    rating: '4.2',
    rating_count: '15.6k',
    grad_a: '#0A1620',
    grad_b: '#14283A',
    grad_c: 'rgba(70,130,180,0.50)',
    icon: 'rainy-outline',
    image_key: 'Silvercascade',
  },
  {
    id: 'kurinji',
    categories: ['culture', 'attractions'],
    name: 'Kurinji Andavar Temple',
    subtitle: 'A hilltop Murugan temple, est. 1936.',
    why_visit:
      'Named for the kurinji flower that blooms once every 12 years. Sweeping views over Palani and Vaigai dam.',
    lat: 10.2475,
    lng: 77.5081,
    rating: '4.5',
    rating_count: '9.2k',
    grad_a: '#1E1005',
    grad_b: '#3C2008',
    grad_c: 'rgba(180,110,40,0.55)',
    icon: 'business-outline',
    image_key: 'Kuruji',
  },
  {
    id: 'bazaar',
    categories: ['shopping', 'culture'],
    name: 'Tibetan & Coronation Bazaar',
    subtitle: 'Hill-station markets for woollens and chocolate.',
    why_visit:
      'Hand-knit shawls, jackets and pashminas at the Tibetan stalls; homemade chocolate, cheese and eucalyptus oil on Bazaar Road.',
    lat: 10.2389,
    lng: 77.4865,
    rating: '4.2',
    rating_count: '6.4k',
    grad_a: '#0E0C16',
    grad_b: '#161224',
    grad_c: 'rgba(120,80,160,0.50)',
    icon: 'bag-handle-outline',
    image_key: null,
  },
];

const ROOMS_CATALOG = [
  {
    id: 'executive',
    name: 'Executive Room',
    category: 'Comfort & Style',
    description:
      'Our well-appointed Executive Rooms offer a harmonious blend of modern comfort and classic Kodaikanal warmth. Overlooking the hotel gardens, each room features warm teak wood accents, plush bedding, and a private seating corner — the perfect retreat after a day on the hills.',
    size_sqft: 280,
    bed_type: 'King Bed',
    max_guests: 2,
    view: 'Garden View',
    price_from: 5000,
    grad_a: '#091A10',
    grad_b: '#142A1A',
    grad_c: 'rgba(55,135,75,0.52)',
    icon: 'bed-outline',
    highlights: ['Garden-facing outlook', 'Blackout curtains', 'Heater · 21°C default'],
    facilities: [
      { icon: 'wifi-outline', label: 'High-Speed WiFi' },
      { icon: 'tv-outline', label: 'LED Cable TV' },
      { icon: 'thermometer-outline', label: 'Air Conditioning & Heater' },
      { icon: 'water-outline', label: '24-hr Hot Water' },
      { icon: 'cafe-outline', label: 'Tea / Coffee Maker' },
      { icon: 'briefcase-outline', label: 'Work Desk' },
      { icon: 'restaurant-outline', label: 'Room Service' },
      { icon: 'shield-checkmark-outline', label: 'In-Room Safe' },
    ],
    image_keys: ['ExecutiveRoom1', 'ExecutiveRoom2', 'ExecutiveRoom3', 'ExecutiveRoom4'],
  },
  {
    id: 'deluxe',
    name: 'Deluxe Double',
    category: 'Valley Views & Space',
    description:
      'Spacious and elegantly furnished, our Deluxe Double rooms step out to a private balcony with sweeping valley panoramas. The warm wood interiors, premium bath amenities, and a dedicated reading corner make this the most popular choice among returning guests.',
    size_sqft: 320,
    bed_type: 'King Bed',
    max_guests: 2,
    view: 'Valley View',
    price_from: 6250,
    grad_a: '#091520',
    grad_b: '#142030',
    grad_c: 'rgba(55,110,175,0.52)',
    icon: 'business-outline',
    highlights: ['Private balcony', 'Valley panorama', 'Premium bath amenities'],
    facilities: [
      { icon: 'wifi-outline', label: 'High-Speed WiFi' },
      { icon: 'tv-outline', label: 'LED Cable TV' },
      { icon: 'thermometer-outline', label: 'Air Conditioning & Heater' },
      { icon: 'water-outline', label: '24-hr Hot Water' },
      { icon: 'cafe-outline', label: 'Tea / Coffee Maker' },
      { icon: 'leaf-outline', label: 'Private Balcony' },
      { icon: 'wine-outline', label: 'Mini Bar' },
      { icon: 'restaurant-outline', label: 'Room Service' },
      { icon: 'shield-checkmark-outline', label: 'In-Room Safe' },
    ],
    image_keys: ['Deluxdouble1', 'Deluxdouble2', 'Deluxdouble3', 'Deluxdouble4', 'Deluxdouble5'],
  },
  {
    id: 'family',
    name: 'Family Room',
    category: 'Space for Everyone',
    description:
      'Generously proportioned and thoughtfully arranged for families, these rooms accommodate up to four guests with ease. A king bed and two comfortable singles share a warm, open-plan space — with ample room for luggage, play and relaxed mornings together.',
    size_sqft: 420,
    bed_type: 'King + 2 Singles',
    max_guests: 4,
    view: 'Garden / Lawn View',
    price_from: 7150,
    grad_a: '#1A100A',
    grad_b: '#2C1A10',
    grad_c: 'rgba(165,100,50,0.52)',
    icon: 'people-outline',
    highlights: ['Sleeps up to 4', 'Extra luggage alcove', 'Child-friendly setup'],
    facilities: [
      { icon: 'wifi-outline', label: 'High-Speed WiFi' },
      { icon: 'tv-outline', label: 'LED Cable TV' },
      { icon: 'thermometer-outline', label: 'Air Conditioning & Heater' },
      { icon: 'water-outline', label: '24-hr Hot Water' },
      { icon: 'cafe-outline', label: 'Tea / Coffee Maker' },
      { icon: 'restaurant-outline', label: 'Room Service' },
      { icon: 'shirt-outline', label: 'Full Wardrobe' },
      { icon: 'bed-outline', label: 'Extra Beds on Request' },
    ],
    image_keys: ['FamilyRoom1', 'FamilyRoom2', 'FamilyRoom3', 'FamilyRoom4', 'FamilyRoom5'],
  },
  {
    id: 'jr-suite',
    name: 'Jr. Suite',
    category: 'A Suite Escape',
    description:
      'A step above in every sense — our Junior Suites offer a dedicated sitting lounge, a soaking bathtub, and premium in-room amenities set against crisp hill views. An ideal choice for a romantic or celebratory stay in the hills.',
    size_sqft: 480,
    bed_type: 'King Bed',
    max_guests: 2,
    view: 'Hill View',
    price_from: 8300,
    grad_a: '#10091A',
    grad_b: '#1C1228',
    grad_c: 'rgba(120,75,185,0.52)',
    icon: 'star-outline',
    highlights: ['Sitting lounge', 'Soaking bathtub', 'Bathrobes & slippers'],
    facilities: [
      { icon: 'wifi-outline', label: 'High-Speed WiFi' },
      { icon: 'tv-outline', label: 'LED Cable TV' },
      { icon: 'thermometer-outline', label: 'Air Conditioning & Heater' },
      { icon: 'water-outline', label: '24-hr Hot Water' },
      { icon: 'cafe-outline', label: 'Tea / Coffee Maker' },
      { icon: 'leaf-outline', label: 'Private Balcony' },
      { icon: 'wine-outline', label: 'Mini Bar' },
      { icon: 'water-outline', label: 'Soaking Bathtub' },
      { icon: 'restaurant-outline', label: 'Room Service' },
      { icon: 'shield-checkmark-outline', label: 'In-Room Safe' },
      { icon: 'ribbon-outline', label: 'Bathrobes & Slippers' },
    ],
    image_keys: ['JRSuiteRoom1', 'JRSuiteRoom2', 'JRSuiteRoom3', 'JRSuiteRoom4', 'JRSuiteRoom5'],
  },
  {
    id: 'suite',
    name: 'Suite',
    category: 'The Pinnacle',
    description:
      'The definitive Hotel Kodai International experience. Our Suites command panoramic views of the Palani Hills from a full living and dining area, with butler service available on request. Handpicked furnishings, a private jacuzzi, and bespoke amenities make this the ultimate retreat in Kodaikanal.',
    size_sqft: 640,
    bed_type: 'King Bed',
    max_guests: 2,
    view: 'Panoramic Hill View',
    price_from: 10000,
    grad_a: '#1A1206',
    grad_b: '#2C1E08',
    grad_c: 'rgba(210,155,45,0.58)',
    icon: 'trophy-outline',
    highlights: ['Panoramic hill views', 'Jacuzzi', 'Living & dining area', 'Butler on request'],
    facilities: [
      { icon: 'wifi-outline', label: 'High-Speed WiFi' },
      { icon: 'tv-outline', label: 'LED Cable TV' },
      { icon: 'thermometer-outline', label: 'Air Conditioning & Heater' },
      { icon: 'water-outline', label: '24-hr Hot Water' },
      { icon: 'cafe-outline', label: 'Tea / Coffee Maker' },
      { icon: 'leaf-outline', label: 'Private Balcony' },
      { icon: 'wine-outline', label: 'Premium Mini Bar' },
      { icon: 'water-outline', label: 'Jacuzzi / Soaking Bath' },
      { icon: 'restaurant-outline', label: 'Priority Room Service' },
      { icon: 'shield-checkmark-outline', label: 'In-Room Safe' },
      { icon: 'person-outline', label: 'Butler Service' },
      { icon: 'ribbon-outline', label: 'Premium Amenity Kit' },
    ],
    image_keys: ['SuiteRoom1', 'SuiteRoom2', 'SuiteRoom3', 'SuiteRoom4', 'SuiteRoom5'],
  },
];

export async function contentRoutes(app: FastifyInstance): Promise<void> {
  app.get('/attractions', async () => ({ data: ATTRACTIONS }));
  app.get('/rooms', async () => ({ data: ROOMS_CATALOG }));
}
