process.env.NODE_ENV = 'test';
process.env.DATABASE_URL ??= 'postgresql://test@localhost:5432/test';
process.env.REDIS_URL ??= 'redis://localhost:6379';
process.env.JWT_PUBLIC_KEY_PATH ??= '../auth-service/secrets/jwt-public.pem';
process.env.RAZORPAY_KEY_ID ??= 'rzp_test_StzbSPi2Kj5eAe';
process.env.RAZORPAY_KEY_SECRET ??= 'XqLR6y2JslOeOC0eyhE2rlNN';
process.env.WORKER_ENABLED ??= 'false';
process.env.HOTEL_NAME ??= 'Test Hotel';
process.env.HOTEL_ADDRESS ??= '123 Test St';
